module.exports.yelp = {
  consumer_key: "DDV0ewsiTHaRGVAyr2i9ZA", 
  consumer_secret: "KGF7__vRo0966s8itGzyEbyoOsA",
  token: "RV2vSB1d3eBwE4OfE3q_10VD5CnL2C9W",
  token_secret: "n1Cfh8YoIj2rvtCPBfPTq6DSNLE"
};

module.exports.bars1 = {
    is_claimed: false,
    rating: 3.5,
    mobile_url: 'http://m.yelp.com/biz/seventy7-culver-city',
    rating_img_url: 'http://s3-media1.fl.yelpcdn.com/assets/2/www/img/5ef3eb3cb162/ico/stars/v1/stars_3_half.png',
    review_count: 202,
    name: 'Seventy7',
    snippet_image_url: 'http://s3-media4.fl.yelpcdn.com/photo/YtRCsOq1RYFYYK0z2WpK2g/ms.jpg',
    rating_img_url_small: 'http://s3-media1.fl.yelpcdn.com/assets/2/www/img/2e909d5d3536/ico/stars/v1/stars_small_3_half.png',
    url: 'http://www.yelp.com/biz/seventy7-culver-city',
    phone: '3105597707',
    snippet_text: 'This rating is mainly for DRINKS, SERVICE and ATMOSPHERE. \n\nI\'ve been here several times usually before, after, or in between visits to nearby restaurants....',
    image_url: 'http://s3-media2.fl.yelpcdn.com/bphoto/S5S67qYMC2hAFSyBFSnLlQ/ms.jpg',
    categories: [ [ 'Lounges', 'lounges' ] ],
    display_phone: '+1-310-559-7707',
    rating_img_url_large: 'http://s3-media3.fl.yelpcdn.com/assets/2/www/img/bd9b7a815d1b/ico/stars/v1/stars_large_3_half.png',
    id: 'seventy7-culver-city',
    is_closed: false,
    location: 
     { city: 'Culver City',
       display_address: [ '3843 Main St', 'Culver City', 'Culver City, CA 90232' ],
       geo_accuracy: 8,
       neighborhoods: [ 'Culver City' ],
       postal_code: '90232',
       country_code: 'US',
       address: [ '3843 Main St' ],
       coordinate: { latitude: 34.0243492, longitude: -118.3945618 },
       state_code: 'CA' } };

module.exports.bars2 = {
    is_claimed: true,
    rating: 4,
    mobile_url: 'http://m.yelp.com/biz/the-wellesbourne-los-angeles',
    rating_img_url: 'http://s3-media4.fl.yelpcdn.com/assets/2/www/img/c2f3dd9799a5/ico/stars/v1/stars_4.png',
    review_count: 588,
    name: 'The Wellesbourne',
    snippet_image_url: 'http://s3-media2.fl.yelpcdn.com/photo/wR8yJuP0dqsjzG19gz7Vfw/ms.jpg',
    rating_img_url_small: 'http://s3-media4.fl.yelpcdn.com/assets/2/www/img/f62a5be2f902/ico/stars/v1/stars_small_4.png',
    url: 'http://www.yelp.com/biz/the-wellesbourne-los-angeles',
    phone: '3104740102',
    snippet_text: 'I have been here a few times but last night it was PACKED. I threw my boyfriend a surprise going away party here and everyone loved it! \n\nThe ambiance is...',
    image_url: 'http://s3-media1.fl.yelpcdn.com/bphoto/awKKdnUvh3liUFpFLj2yNQ/ms.jpg',
    categories: [ [ 'Lounges', 'lounges' ] ],
    display_phone: '+1-310-474-0102',
    rating_img_url_large: 'http://s3-media2.fl.yelpcdn.com/assets/2/www/img/ccf2b76faa2c/ico/stars/v1/stars_large_4.png',
    id: 'the-wellesbourne-los-angeles',
    is_closed: false,
    location: 
     { city: 'Los Angeles',
       display_address: 
        [ '10929 W Pico Blvd',
          'West Los Angeles',
          'Los Angeles, CA 90064' ],
       geo_accuracy: 8,
       neighborhoods: [ 'West Los Angeles' ],
       postal_code: '90064',
       country_code: 'US',
       address: [ '10929 W Pico Blvd' ],
       coordinate: { latitude: 34.0393070876598, longitude: -118.430363461375 },
       state_code: 'CA' } };

module.exports.restaurants1 = {
    is_claimed: false,
    rating: 4.5,
    mobile_url: 'http://m.yelp.com/biz/rubios-cafe-los-angeles',
    rating_img_url: 'http://s3-media2.fl.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png',
    review_count: 57,
    name: 'Rubio\'s Cafe',
    snippet_image_url: 'http://s3-media1.fl.yelpcdn.com/photo/bhmpAWBnjjZl2x1151_Uvg/ms.jpg',
    rating_img_url_small: 'http://s3-media2.fl.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png',
    url: 'http://www.yelp.com/biz/rubios-cafe-los-angeles',
    phone: '3102021770',
    snippet_text: 'I LOVE this place!!!\n\nThe food is reasonably priced, and consistently delicious. My wife and I eat there often. It\'s family owned and operated. This fact...',
    image_url: 'http://s3-media2.fl.yelpcdn.com/bphoto/f0-t4Piuu2fJw1vxFCZ4Ew/ms.jpg',
    categories: [ [ 'Mexican', 'mexican' ] ],
    display_phone: '+1-310-202-1770',
    rating_img_url_large: 'http://s3-media4.fl.yelpcdn.com/assets/2/www/img/9f83790ff7f6/ico/stars/v1/stars_large_4_half.png',
    id: 'rubios-cafe-los-angeles',
    is_closed: false,
    location: 
     { city: 'Los Angeles',
       display_address: [ '3380 S Robertson Blvd', 'Palms', 'Los Angeles, CA 90034' ],
       geo_accuracy: 8,
       neighborhoods: [ 'Palms' ],
       postal_code: '90034',
       country_code: 'US',
       address: [ '3380 S Robertson Blvd' ],
       coordinate: { latitude: 34.0290718, longitude: -118.3908615 },
       state_code: 'CA' } };

module.exports.restaurants2 = {
    is_claimed: true,
    rating: 4,
    mobile_url: 'http://m.yelp.com/biz/jackson-market-culver-city',
    rating_img_url: 'http://s3-media4.fl.yelpcdn.com/assets/2/www/img/c2f3dd9799a5/ico/stars/v1/stars_4.png',
    review_count: 424,
    name: 'Jackson Market',
    snippet_image_url: 'http://s3-media4.fl.yelpcdn.com/photo/0Dhbwz_IWuM2z7COciOtxw/ms.jpg',
    rating_img_url_small: 'http://s3-media4.fl.yelpcdn.com/assets/2/www/img/f62a5be2f902/ico/stars/v1/stars_small_4.png',
    url: 'http://www.yelp.com/biz/jackson-market-culver-city',
    phone: '3104258426',
    snippet_text: 'Adorable hidden mid-block neighborhood breakfast and lunch spot with a full market and a perfectly serene, "how the F#%& am I still in LA and it\'s THIS...',
    image_url: 'http://s3-media4.fl.yelpcdn.com/bphoto/9qh2LCm0R5MnG2QceearXg/ms.jpg',
    categories: [ [ 'Sandwiches', 'sandwiches' ], [ 'Grocery', 'grocery' ] ],
    display_phone: '+1-310-425-8426',
    rating_img_url_large: 'http://s3-media2.fl.yelpcdn.com/assets/2/www/img/ccf2b76faa2c/ico/stars/v1/stars_large_4.png',
    id: 'jackson-market-culver-city',
    is_closed: false,
    location: 
     { city: 'Culver City',
       display_address: [ '4065 Jackson Ave', 'Culver City', 'Culver City, CA 90232' ],
       geo_accuracy: 8,
       neighborhoods: [ 'Culver City' ],
       postal_code: '90232',
       country_code: 'US',
       address: [ '4065 Jackson Ave' ],
       coordinate: { latitude: 34.017159, longitude: -118.397263 },
       state_code: 'CA' } };
       